server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.153.129:3306/tensquare_base?charcterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
